### ISSUE TITLE
質問:binフォルダについて

### ISSUE THREAD

**Issue by taisan11** [kusaanko/OldMCPatcher#1]
旧マインクラフトではbinフォルダがあり、binフォルダ直下にSinglePlayerCommandsのworldedit.jarを入れなきゃいけないのですが、こちらのMODでは、binフォルダは追加されるでしょうか?

**Comment by kusaanko** [comment]
binフォルダは自動的に追加されませんが、自分で1.2.5用SinglePlayerCommandsのWorldEdit.jarをゲームディレクトリ直下(ランチャーで指定またはデフォルト(.minecraft))にbinフォルダを作成しそこに配置することでWorldEditを使用することが可能でした。

**Comment by taisan11** [comment]
ありがとうございます!
